before_script: &vpn
  - which openvpn || (apt-get update -y -qq && apt-get install -y -qq openvpn && apt-get install -y -qq iputils-ping)
  - cat <<< $vpn_cert > /etc/openvpn/client.ovpn
  - openvpn --config /etc/openvpn/client.ovpn  --daemon # Start openvpn with config as a deamon.
  - sleep 30s # Wait for some time so the vpn can connect before doing anything else.
  - systemctl restart systemd-resolved.service
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  
image: ubuntu:latest
stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  when: manual
  before_script: *vpn
  script:
    - echo "access machine"
    - ssh massimo@gollo1.particles.dieei.unict.it "touch /home/massimo/from_ci.txt"


