stages:          # List of stages for jobs, and their order of execution
  - build-cloud
  - build-edge
  - run-load
  - collect-data
  - cleanup

cloud-minikube-setup:
  stage: build-cloud
  script: 
    - cd $CI_PROJECT_DIR/helpers/scripts && ./minikube_setup.sh
  tags:
    - "cloud-runner"
  when: manual

cloud-helm-deploy:
  stage: build-cloud
  needs: 
    - cloud-minikube-setup
  script:
    - cd $CI_PROJECT_DIR/helpers/scripts && ./deploy_chart.sh
  tags:
    - "cloud-runner"

cloud-deploy-kps:
  stage: build-cloud
  needs: 
    - cloud-minikube-setup
  script:
    - cd $CI_PROJECT_DIR/helpers/scripts && ./deploy_kps.sh cloud
  tags:
    - "cloud-runner"

cloud-seed:
  stage: build-cloud
  needs: 
    - cloud-helm-deploy
    - cloud-deploy-kps
    - cloud-minikube-setup
  script:
    - cd $CI_PROJECT_DIR/helpers/scripts && ./seed.sh
  tags:
    - "cloud-runner"

edge-minikube-setup:
  needs:
    - cloud-helm-deploy
  stage: build-edge
  script:
    - cd $CI_PROJECT_DIR/helpers/scripts && ./minikube_setup.sh
  tags:
    - "edge-runner"
 
edge-helm-deploy:
  stage: build-edge
  needs: [edge-minikube-setup]
  script:
    - cd $CI_PROJECT_DIR && helm install vp-edge vp-cloud -f variants/default/values.edge-particles.yaml --disable-openapi-validation
    - kubectl wait --for=condition=ready pod -l app=videoserver-videomanagement --timeout=10m
    - cd $CI_PROJECT_DIR/helpers/scripts && ./deploy_kps.sh edge
  tags:
    - "edge-runner"

start-load: 
    stage: run-load
    script: 
      - echo "starting load"
      - sleep 180
    needs: [edge-helm-deploy]
    tags: 
      - "edge-runner" #do not exist yes

collect-data-edge:
  stage: collect-data
  needs:
    - start-load
  script:
    - cd $CI_PROJECT_DIR/helpers/scripts && ./collect_metrics.sh
  tags: 
    - "edge-runner"
  artifacts:
    untracked: true
    paths:
      - $CI_PROJECT_DIR/helpers/prom-data/

collect-data-cloud:
  stage: collect-data
  needs:
    - start-load
  script:
    - cd $CI_PROJECT_DIR/helpers/scripts && ./collect_metrics.sh
  tags:
    - "cloud-runner"
  artifacts:
    untracked: true
    paths:
      - $CI_PROJECT_DIR/helpers/prom-data/

cleanup-edge:
  stage: cleanup
  needs: 
    - collect-data-edge
  script:
    - minikube delete 
  tags:
    - "edge-runner"

cleanup-cloud:
  stage: cleanup
  script:
    - minikube delete 
  tags:
    - "cloud-runner"
  needs:
    - collect-data-cloud

start-load-test: 
    stage: run-load
    script: 
      - echo "starting load"
      - cd ~
      - ./load-generator -c 11 -u http://edge.gollo2.particles.dieei.unict.it
    tags: 
      - "load-runner" #do not exist yes
    when: manual
