stages:          # List of stages for jobs, and their order of execution
  - build-cloud
  - build-edge
  - run-load-gen
  - collect-metrics

cloud-startup-job:      
  stage: build-cloud
  script:
    - cd $CI_PROJECT_DIR/helpers/starter && ./cloud_setup.sh
  before_script:
    - docker login -u $GITLAB_USER -p $PERSONAL_ACCESS_TOKEN $CI_REGISTRY
  tags:
    - "cloud"
  when: manual

cloud-cleanup-job:  
  stage: build-cloud  
  script:
    - minikube delete 
  tags:
    - "cloud"
  when: manual

edge-startup-job:      
  stage: build-edge
  script:
    - echo "shoud start edge with version.."
  before_script:
    - docker login -u $GITLAB_USER -p $PERSONAL_ACCESS_TOKEN $CI_REGISTRY
  tags:
    - "edge"
  when: manual

