stages:          # List of stages for jobs, and their order of execution
  - cloud
  - edge
  - cleanup
  - run-load

deploy-cloud-job:
  stage: cloud
  script:
    - cd $CI_PROJECT_DIR/helpers/starter && ./cloud_setup.sh
  before_script:
    - docker login -u $GITLAB_USER -p $PERSONAL_ACCESS_TOKEN $CI_REGISTRY
  tags:
    - "cloud-runner"
  when: manual

cleanup-job:
  stage: cleanup
  script:
    - minikube delete 
  tags:
    - "cloud"
    - "edge"
  when: manual

deploy-edge-job:
  stage: edge
  needs: [deploy-cloud-job]
  script:
    - cd $CI_PROJECT_DIR && helm install vp-edge vp-cloud -f variants/default/values.edge-particles.yaml --disable-openapi-validation
  before_script:
    - docker login -u $GITLAB_USER -p $PERSONAL_ACCESS_TOKEN $CI_REGISTRY
  tags:
    - "edge"

