before_script: &vpn
  - cat <<< $vpn_cert > /home/client.conf
  - which openvpn || (apt-get update -y -qq && apt-get install iputils-ping -y && apt-get install -y -qq openvpn) # Install openvpn if not available.
  - openvpn --config /home/client.conf --daemon # Start openvpn with config as a deamon.
  - sleep 10s # Wait for some time so the vpn can connect before doing anything else.
  - ping -c 1 gollo1.particles.dieei.unict.it
  
image: ubuntu:latest
stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  when: manual
  before_script: *vpn
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."


