stages:          # List of stages for jobs, and their order of execution
  - build-cloud
  - edge
  - run-load
  - cleanup

cloud-minikube-setup:
  stage: build-cloud
  script:
    - cd $CI_PROJECT_DIR/helpers/starter && ./minikube_setup.sh
  tags:
    - "cloud-runner"
  when: manual

cloud-helm-deploy:
  stage: build-cloud
  needs: [cloud-minikube-setup]
  script:
    - cd $CI_PROJECT_DIR/helpers/starter && ./deploy_chart.sh
  tags:
    - "cloud-runner"

cloud-seed:
  stage: build-cloud
  needs: [cloud-helm-deploy]
  script:
    - cd $CI_PROJECT_DIR/helpers/starter && ./seed.sh
  tags:
    - "cloud-runner"

cloud-deploy-kps:
  stage: build-cloud
  needs: [cloud-minikube-setup]
  script:
    - cd $CI_PROJECT_DIR/helpers/starter && ./deploy_kps.sh
  tags:
    - "cloud-runner"

deploy-edge-job:
  stage: edge
  #needs: [deploy-cloud-job, cleanup-edge-job]
  script:
    - minikube start --memory 16384 --cpus 16 --kubernetes-version=v1.19.16
    - minikube addons enable ingress
    - kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
    - cd $CI_PROJECT_DIR && helm install vp-edge vp-cloud -f variants/default/values.edge-particles.yaml --disable-openapi-validation
    - kubectl wait --for=condition=ready pod -l app=videoserver-videomanagement --timeout=10m
  tags:
    - "edge-runner"
  when: manual

cleanup-edge-job:
  stage: cleanup
  script:
    - minikube delete 
  tags:
    - "edge-runner"
  when: manual

cleanup-cloud-job:
  stage: cleanup
  script:
    - minikube delete 
  tags:
    - "cloud-runner"
  when: manual

start-load: 
    stage: run-load
    script: 
      - echo "starting load"
    needs: [deploy-edge-job]
    when: manual #TODO remove me
    tags: 
      - "load-runner" #do not exist yes
