apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.apiGateway.name }}
spec:
  ports:
    - port: {{ .Values.services.apiGateway.port }}
  selector:
    app: videoserver-gateway
{{- if eq .Values.vms.isCloud "true" }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: expose-proxy
spec:
  host: {{ .Values.routes.cloudURL }}
  to:
    kind: Service
    name: {{ .Values.services.apiGateway.name }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: videoserver-gateway
spec:
    selector:
        matchLabels:
            app: videoserver-gateway
    template:
        metadata:
          labels:
            app: videoserver-gateway
        spec:
            containers:
                - name: videoserver-gateway
                  image: {{.Values.images.cloudGateway}}
                  ports:
                  - containerPort: 8081
                  volumeMounts:
                      - mountPath: /videofiles
                        name: videoserver-videofiles
                      - mountPath: /logs
                        name: videoserver-logs
            volumes:
              - name: videoserver-videofiles
                persistentVolumeClaim:
                  claimName: videoserver-videofiles
              - name: videoserver-logs
                persistentVolumeClaim:
                  claimName: videoserver-logs
