apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: videoserver-videofiles
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  {{ if eq .Values.isMinikube true }}
  volumeName: videofiles-pv
  {{ end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: videoserver-logs
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  {{ if eq .Values.isMinikube true }}
  volumeName: logs-pv
  {{ end }}
  #volumeName: logs-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: videoserver-video
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  {{ if eq .Values.isMinikube true }}
  volumeName: videos-pv
  {{ end }}
#volumeName: videos-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: mongodb-data
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  {{ if eq .Values.isMinikube true }}
  volumeName: mongo-pv
  {{ end }}
  #volumeName: mongo-pv
