{{ if or (.Values.isMinikube) (.Values.isGkeCkoud)  }}
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.namespace }}
  name: mongo-pv
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/cloud/mongodata
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.namespace }}
  name: logs-pv
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/cloud/logs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.namespace }}
  name: videos-pv
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/cloud/videos
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: videofiles-pv
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/cloud/videofiles
    type: DirectoryOrCreate
  {{- end }}