apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace | default "default" }}
  name: mongo-express-svc
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace | default "default" }}
  name: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: {{ .Values.mongodb.username | default "root" }}
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: {{ .Values.mongodb.password | default "toor" }}
            - name: ME_CONFIG_MONGODB_SERVER
              value: {{ .Values.mongodb.databaseName | default "mongodb" }}

