routes:
  # This is the domain to which a client is redirected if the Edge cannot serve her request
  cloudURL: 'cloud.massimogollo.it'
  # This is the domain to which expose the main route used by the clients (actually this would be achieved by a location transparency DNS configuration)
  edgeURL: 'edge.massimogollo.it'

isOpenShift: false
isMinikube: true

vms:
  isCloud: "false" # Let the micro-services know they are executing in the Edge
  maxVideo: 10 # Set limits of the capped collection (i.e., the maximum number of video stored in the Edge, leveraging a LRU cache retention policy)
  variantType: "0" # Set the VMS to act as the Edge Cache Variant
  needKafkaBeans: "false"

#Parameters of the capped video collection
mongodb:
  videoCollectionSize: 10000
  videoCollectionMaxDocs: 10

vps: # Not used here since Cache Variant does not deploy any VPS
  replicas: 1

lb:
  # Sets the maximum number of concurrent users an Edge Deployment can serve
  maxConcurrentUsers: 2

# Images url for the containers
images:
  edgeLb: docker.io/aleskandro/video-server:edge-lb
  cloudGateway: docker.io/massigollo/video-server:cloud-gateway
  cloudVms: docker.io/massigollo/video-server:cloud-vms
  cloudVps: docker.io/massigollo/video-server:cloud-vps
  mongoDb: docker.io/bitnami/mongodb:4.4
  kafka: wurstmeister/kafka:2.11-2.0.0
  zookeeper: library/zookeeper:3.4.13
  # This image is used by default for mongoDb if isOpenShift is set to true
  openShiftMongoDb: docker-registry.default.svc:5000/openshift/mongodb