resources:
  vps:
    limits:
      cpu: 500m
      memory: 3Gi
    requests:
      cpu: 300m
      memory: 2Gi

routes:
  cloudURL: 'cloud.gollo1.particles.dieei.unict.it'
  edgeURL: 'edge.gollo2.particles.dieei.unict.it'

namespace: default

# Note: the following two values cannot be together set at true
# If you are deploing on openshift, set isOpenshift at true and isMinikube at false
# If you are deploying on a generic k8s cluster, set both at false (dynamic provisioning should be used and have a
#  look at the storageClassName to use
# If you are deploying on Minikube set isOpenshift at true and isMinikube at true

# If you are deploying on OpenShift, keep this true (Note, it's a string)
isOpenShift: false
# If you are deploying on Minikube, set this true
isMinikube: true
isGkeCkoud: false

# Images url for the containers
images:
  cloudGateway: quay.io/massigollo/video-server:cloud-gateway
  cloudVms: quay.io/massigollo/video-server:cloud-vms
  cloudVps: quay.io/massigollo/video-server:cloud-vps
  mongoDb: quay.io/massigollo/video-server:mongodb
  kafka: quay.io/massigollo/video-server:kafka
  zookeeper: quay.io/massigollo/video-server:zookeeper