resources:
  vps:
    limits:
      cpu: 500m
      memory: 3Gi
    requests:
      cpu: 300m
      memory: 2Gi

routes:
  cloudURL: 'cloud.gollo1.particles.dieei.unict.it'
  edgeURL: 'edge.gollo2.particles.dieei.unict.it'

namespace: default

# Note: the following two values cannot be together set at true
# If you are deploing on openshift, set isOpenshift at true and isMinikube at false
# If you are deploying on a generic k8s cluster, set both at false (dynamic provisioning should be used and have a
#  look at the storageClassName to use
# If you are deploying on Minikube set isOpenshift at true and isMinikube at true

# If you are deploying on OpenShift, keep this true (Note, it's a string)
isOpenShift: false
# If you are deploying on Minikube, set this true
isMinikube: true
isGkeCkoud: false

# Images url for the containers
images:
  cloudGateway: registry.gitlab.com/massimo-gollo/mora-deployment:cloud-gateway
  cloudVms: registry.gitlab.com/massimo-gollo/mora-deployment:cloud-vms
  cloudVps: registry.gitlab.com/massimo-gollo/mora-deployment:cloud-vps
  mongoDb: registry.gitlab.com/massimo-gollo/mora-deployment/mongodb:4.4
  kafka: registry.gitlab.com/massimo-gollo/mora-deployment/kafka:2.11-2.0.0
  zookeeper: registry.gitlab.com/massimo-gollo/mora-deployment/zookeeper:3.4.13