routes:
  # This is the domain to which a client is redirected if the Edge cannot serve her request
  cloudURL: 'cloud.gollo1.particles.dieei.unict.it'
  edgeURL: 'edge.gollo2.particles.dieei.unict.it'

noDNSServerForCloud: false
isOpenShift: false
isMinikube: true

vms:
  isCloud: "false" # Let the micro-services know they are executing in the Edge
  maxVideo: 5
  variantType: "0" # Set the VMS to act as the Edge Cache Variant
  needKafkaBeans: "false"

#Parameters of the capped video collection
mongodb:
  videoCollectionSize: 10000
  videoCollectionMaxDocs: 5

vps: # Not used here since Cache Variant does not deploy any VPS
  replicas: 1

lb:
  # Sets the maximum number of concurrent users an Edge Deployment can serve
  maxConcurrentUsers: 100

# Images url for the containers
images:
  cloudGateway: quay.io/massigollo/video-server:cloud-gateway
  cloudVms: quay.io/massigollo/video-server:cloud-vms4
  cloudVps: quay.io/massigollo/video-server:cloud-vps
  mongoDb: quay.io/massigollo/video-server:mongodb
  kafka: quay.io/massigollo/video-server:kafka
  zookeeper: quay.io/massigollo/video-server:zookeeper
