version: '3.8'

x-common-config: &common-settings-config
  restart: always

x-port-mapping:
  prometheus: &prometheus-ports
    - 9090:5000

volumes:
  prometheus_data: {}

services:
  prometheus:
    <<: *common-settings-config
    ports: *prometheus-ports
    image: prom/prometheus
    user: root
    volumes:
      - prometheus_data:/data
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--storage.tsdb.path=/data'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
      - '--web.enable-lifecycle'
      - '--web.listen-address=:5000'
      - '--web.enable-admin-api'