# Example of values.yaml file to deploy edge cache-only variant to minikube
routes:
  # Change the following accordingly to your needs
  cloudURL: 'cloud-vms-1.minikube.cloudhost'
  edgeURL: 'edge-service.minikube.edgehost'

vms:
  isCloud: "false" # Let the micro-services know they are executing in the Edge
  maxVideo: 10 # Set limits of the capped collection (i.e., the maximum number of video stored in the Edge, leveraging a LRU cache retention policy)
  variantType: "0" # Set the VMS to act as the Edge Cache Variant
  needKafkaBeans: "false"


vps: # Not used here since Cache Variant does not deploy any VPS
  replicas: 1


isOpenShift: "false"
isMinikube: true

# Parameters of the capped video collection
mongodb:
  videoCollectionSize: 10000
  videoCollectionMaxDocs: 10

lb:
  # Sets the maximum number of concurrent users an Edge Deployment can serve
  maxConcurrentUsers: 2
